
version: '2.1'
services:
  db:
      image: mysql:5.7
      command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
      restart: always
      ports:
        - "3306:3306"
      container_name: openmrs-db
      healthcheck:
        test: "exit 0"
      environment:
        - MYSQL_DATABASE=openmrs
        - MYSQL_ROOT_PASSWORD=openmrs
        - MYSQL_USER=root
        - MYSQL_PASSWORD=openmrs
        - MYSQL_ROOT_HOST=%    # Allow docker containers to connect to mysql
      volumes:
        #- ./data:/var/lib/mysql
        - ./utils/dbdump:/docker-entrypoint-initdb.d # will execute any sql dumped here
  openmrs-server:
      image: partnersinhealth/openmrs-server:latest
      container_name: openmrs-server
      depends_on:
        - db
      ports:
        - "8087:8080"
      env_file:
          - ./.env
      volumes:
        - ./distribution:/openmrs/distribution
        - ./data:/openmrs/data